Trabajo_final/config/routes.rb
Rails.application.routes.draw do
  resources :appointments
  resources :users
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
  }, :path_prefix => 'devise'

  #make a route that allows client to see their appointments
  get '/appointments', to: 'appointments#index', as: 'client_appointments'
  #make a route that allows client to cancel an appointment
  patch '/appointments/:id/cancel', to: 'appointments#update', as: 'cancel_appointment', :defaults => { :status => 'canceled' }
  patch '/appointments/:id/finish', to: 'appointments#update', as: 'finish_appointment', :defaults => { :status => 'finished' }

  resources :branches, except: [:show] do
    resources :schedules, except: [:show]
    resources :appointments, except: [:show]
  end

  root 'home#index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

Trabajo_final/app/models/branch.rb
class Branch < ApplicationRecord
  has_many :schedules, dependent: :destroy
  has_many :appointments
  has_many :users, dependent: :destroy
  validates :name, :address, :telephone, presence: {message: "El campo es obligatorio"}

  def to_s
    name
  end
end

Trabajo_final/app/controllers/branches_controller.rb
class BranchesController < ApplicationController
  before_action :authenticate_user!
  load_and_authorize_resource
  before_action :set_branch, only: %i[ show edit update destroy ]

  # GET /branches or /branches.json
  def index
    @branches = Branch.all
  end


  # GET /branches/new
  def new
    @branch = Branch.new
  end

  # GET /branches/1/edit
  def edit
  end

  # POST /branches or /branches.json
  def create
    @branch = Branch.new(branch_params)

    respond_to do |format|
      if @branch.save
        format.html { redirect_to branches_url, notice: "Sucursal #{@branch.name} creada" }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /branches/1 or /branches/1.json
  def update
    respond_to do |format|
      if @branch.update(branch_params)
        format.html { redirect_to branches_url, notice: "Sucursal #{@branch.name} actualizada" }
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /branches/1 or /branches/1.json
  def destroy
    if @branch.appointments.where(status: :pending).empty?
      @branch.appointments.where.not(status: :pending).destroy_all
      name=@branch.name
      @branch.destroy
      respond_to do |format|
        format.html { redirect_to branches_url, notice: "Sucursal #{name} borrada" }
      end
    else
      redirect_to branches_url, notice: "La sucursal no puede ser borrada, hay turnos pendientes"
    end

  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_branch
    @branch = Branch.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def branch_params
    params.require(:branch).permit(:name, :address, :telephone)
  end
end

Trabajo_final/app/helpers/branches_helper.rb
module BranchesHelper
end

Trabajo_final/app/views/branches/_branch.html.erb
<div id="<%= dom_id branch %>">
  <p>
    <strong>Nombre:</strong>
    <%= branch.name %>
  </p>
  <p>
    <strong>Direccion:</strong>
    <%= branch.address %>
  </p>

  <p>
    <strong>Telefono:</strong>
    <%= branch.telephone %>
  </p>

</div>

Trabajo_final/app/views/branches/_form.html.erb
<%= form_with(model: branch) do |form| %>

  <div class="d-flex justify-content-center">
    <div>
      <%= render "shared/error_messages", resource: branch %>
      <div class="card bg-danger " style="width: 20rem">
        <div class="card-body">
          <div>
            <%= form.label :Nombre, style: "display: block" %>
            <%= form.text_field :name, class: "form-control" %>
          </div>

          <div>
            <%= form.label :Dirección, style: "display: block" %>
            <%= form.text_area :address, rows: 2, class: "form-control" %>
          </div>

          <div>
            <%= form.label :Telefono, style: "display: block" %>
            <%= form.number_field :telephone, class: "form-control" %>
          </div>
        </div>
        <div class="card bg-danger ">
          <div class="list-group list-group-flush d-flex">
            <%= form.submit "Confirmar", class: "list-group-item bg-danger" %>
            <%= link_to "Volver", branches_path, class: "list-group-item bg-danger", style: "text-align:center" %>
          </div>
        </div>
      </div>
    </div>
  </div>
<% end %>

Trabajo_final/app/views/branches/edit.html.erb
<h1 class="text-center m-4">Editando Sucursal</h1>
<%= render "form", branch: @branch %>

Trabajo_final/app/views/branches/index.html.erb
<h1 class="text-center m-4">Sucursales</h1>

<div class="d-flex justify-content-center">
  <% if can? :create, Branch %>
    <%= link_to "Nueva Sucursal", new_branch_path, class: "btn btn-secondary m-2" %>
  <% end %>
</div>
<div class="d-flex justify-content-center">
  <div id="appointments" class="d-flex flex-column m-4" style="width: 40rem">
    <% @branches.each do |branch| %>
      <div class="card mb-3 bg-danger ">
        <div class="row no-gutters">
          <div class="col-md-8">
            <div class="card-body">
              <%= render branch %>
            </div>
          </div>
          <div class="col-md-4 d-flex align-items-center justify-content-center">
            <div class="d-flex flex-column">
              <% if can? :edit, Branch %>
                <%= link_to "Editar", edit_branch_path(branch),class: "btn btn-secondary align-self-center m-1 w-100"%>
                <%= link_to 'Borrar', branch, class: "btn btn-secondary align-self-center m-1 w-100", method: :delete, data: { turbo_method: "delete", confirm: '¿Seguro que desea borrar la sucursal?' } %>
              <% end %>
              <% if can?(:create, Appointment) && current_user.client?%>
                <%= link_to "Pedir Turno", new_branch_appointment_path(branch), class: "btn btn-secondary align-self-center m-1 w-100" %>
              <% end %>
              <% if can? :index, Schedule %>
                <%= link_to "Horarios", branch_schedules_path(branch), class: "btn btn-secondary align-self-center m-1 w-100" %>
              <% end %>
            </div>
          </div>
        </div>

      </div>
    <% end %>
  </div>
</div>

Trabajo_final/app/views/branches/new.html.erb
<h1 class="text-center m-4">Creando Sucursal</h1>
<%= render "form", branch: @branch %>