Trabajo_final/config/routes.rb
Rails.application.routes.draw do
  resources :appointments
  resources :users
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
  }, :path_prefix => 'devise'

  #make a route that allows client to see their appointments
  get '/appointments', to: 'appointments#index', as: 'client_appointments'
  #make a route that allows client to cancel an appointment
  patch '/appointments/:id/cancel', to: 'appointments#update', as: 'cancel_appointment', :defaults => { :status => 'canceled' }
  patch '/appointments/:id/finish', to: 'appointments#update', as: 'finish_appointment', :defaults => { :status => 'finished' }

  resources :branches, except: [:show] do
    resources :schedules, except: [:show]
    resources :appointments, except: [:show]
  end

  root 'home#index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

Trabajo_final/app/models/schedule.rb
class Schedule < ApplicationRecord
  DIAS = %w[Domingo Lunes Martes Miercoles Jueves Viernes Sabado]

  def self.for_day (date)
    find_by day: DIAS[date.wday]
  end

  belongs_to :branch
  validates :day, :start_time, :end_time, presence:  {message: "El campo es obligatorio"}
  validates :end_time, comparison: { greater_than: :start_time, message: ": El tiempo de finalización debe ser mayor al de inicio" }
  validates :day, inclusion: { in: DIAS, message: "%{value} no es un dia" }

  validates :day, uniqueness: { scope: :branch_id,
                                message: "Ya existe un horario para este dia" }
end

Trabajo_final/app/controllers/schedules_controller.rb
class SchedulesController < ApplicationController
  before_action :authenticate_user!
  load_and_authorize_resource
  before_action :set_branch
  before_action :set_schedule, only: [:edit, :update, :destroy]

  # GET branches/1/schedules
  def index
    @schedules = @branch.schedules
  end

  # GET branches/1/schedules/new
  def new
    @schedule = @branch.schedules.build
  end

  # GET branches/1/schedules/1/edit
  def edit
  end

  # POST branches/1/schedules
  def create
    @schedule = @branch.schedules.build(schedule_params)

    if @schedule.save
      redirect_to(branch_schedules_url(@branch), notice: "Horario del #{@schedule.day} creado")
    else
      render action: 'new'
    end
  end

  # PUT branches/1/schedules/1
  def update
    respond_to do |format|
      if @schedule.update(schedule_params)
        format.html { redirect_to branch_schedules_url(@branch), notice: "Horario del #{@schedule.day} actualizado" }
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  # DELETE branches/1/schedules/1
  def destroy
    day = @schedule.day
    @schedule.destroy
    respond_to do |format|
      format.html { redirect_to branch_schedules_url(@branch), notice: "Horario del #{day} borrado" }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_branch
    @branch = Branch.find(params[:branch_id])
  end

  def set_schedule
    @schedule = @branch.schedules.find(params[:id])
  end

  # Only allow a trusted parameter "white list" through.
  def schedule_params
    params.require(:schedule).permit(:day, :start_time, :end_time)
  end
end

Trabajo_final/app/views/schedules/_form.html.erb
<%= form_with(model: [@schedule.branch, @schedule]) do |f| %>

  <div class="d-flex justify-content-center">
    <div>
      <%= render "shared/error_messages", resource: @schedule %>
      <div class="d-flex justify-content-center">
        <div class="card bg-danger " style="width: 20rem">
          <div class="card-body">
            <div class="field">
              <%= f.label :day %><br/>
              <%= f.text_field :day, class: "form-control" %>
            </div>
            <div class="field">
              <%= f.label :start_time %><br/>
              <%= f.time_field :start_time, class: "form-control" %>
            </div>
            <div class="field">
              <%= f.label :end_time %><br/>
              <%= f.time_field :end_time, class: "form-control" %>
            </div>
          </div>
          <div class="card bg-danger ">
            <div class="list-group list-group-flush d-flex">
              <%= f.submit "Confirmar", class: "list-group-item bg-danger" %>
              <%= link_to "Volver", branch_schedules_path(@branch), class: "list-group-item bg-danger", style: "text-align:center" %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
<% end %>

Trabajo_final/app/views/schedules/edit.html.erb
<h1 class="text-center m-4">Editando Horario</h1>
<%= render 'form' %>

Trabajo_final/app/views/schedules/index.html.erb
<h1 class="text-center m-4">Horarios de <%= @branch.name %></h1>
<div class="d-flex justify-content-center">

  <table class="table table-hover" style="width: 80rem">
    <tr>
      <th class="table-light">Día</th>
      <th class="table-light">Inicio</th>
      <th class="table-light">Fin</th>
      <% if can? :destroy, Schedule %>
        <th class="table-light">Acciones</th>
        <th class="table-light"></th>
      <% end %>
    </tr>

    <% @schedules.each do |schedule| %>
      <tr>
        <td class="table-light"><%= schedule.day %></td>
        <td class="table-light"><%= schedule.start_time.to_s(:time) %></td>
        <td class="table-light"><%= schedule.end_time.to_s(:time) %></td>
        <% if can? :destroy, Schedule %>
          <td class="table-light" style="width: 15rem"><%= link_to 'Editar', edit_branch_schedule_path(schedule.branch, schedule) %></td>
          <td class="table-light" style="width: 15rem"><%= link_to 'Borrar', [schedule.branch, schedule], method: :delete, data: { turbo_method: "delete", confirm: 'Estás seguro?' } %></td>

        <% end %>
      </tr>
    <% end %>
    <tr>
      <th class="table-light"></th>
      <th class="table-light"><%= link_to 'Volver', branches_path, class: "btn btn-secondary m-1" %></th>
      <th class="table-light"></th>
      <% if can? :create, Schedule %>
        <th class="table-light"><%= link_to 'Crear Horario', new_branch_schedule_path(params[:branch_id]), class: "btn btn-secondary m-1" %></th>
        <th class="table-light"></th>
      <% end %>


    </tr>
  </table>
</div>

Trabajo_final/app/views/schedules/new.html.erb
<h1 class="text-center m-4">Nuevo Horario</h1>

<%= render 'form' %>