Trabajo_final/config/routes.rb
Rails.application.routes.draw do
  resources :appointments
  resources :users
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
  }, :path_prefix => 'devise'

  #make a route that allows client to see their appointments
  get '/appointments', to: 'appointments#index', as: 'client_appointments'
  #make a route that allows client to cancel an appointment
  patch '/appointments/:id/cancel', to: 'appointments#update', as: 'cancel_appointment', :defaults => { :status => 'canceled' }
  patch '/appointments/:id/finish', to: 'appointments#update', as: 'finish_appointment', :defaults => { :status => 'finished' }

  resources :branches, except: [:show] do
    resources :schedules, except: [:show]
    resources :appointments, except: [:show]
  end

  root 'home#index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

Trabajo_final/app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-md bg-danger">
  <%= link_to image_tag("RubyBankLogo.png", class: "img-fluid"), root_path, class: "navbar-brand m-2", style: "width:15rem" %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <% if user_signed_in? %>
    <div class="collapse navbar-collapse d-flex">
      <ul class="navbar-nav mr-auto">
        <% if can? :index, User %>
          <li class="nav-item">
            <%= link_to 'Usuarios', users_path, class: "nav-link", style: "font-size: 1.5rem !important" %>
          </li>
        <% end %>
        <% if can? :index, Branch %>
          <li class="nav-item">
            <%= link_to 'Sucursales', branches_path, class: "nav-link", style: "font-size: 1.5rem !important" %>
          </li>
        <% end %>
        <% if can? :index, Appointment %>
          <li class="nav-item">
            <% if current_user.staff? %>
              <%= link_to 'Turnos', branch_appointments_path(branch_id: current_user.branch_id), class: "nav-link", style: "font-size: 1.5rem !important" %>
            <% else %>
              <%= link_to 'Turnos', client_appointments_path, class: "nav-link", style: "font-size: 1.5rem !important" %>
            <% end %>
          </li>
        <% end %>
      </ul>
      <div class="d-flex ms-auto">
        <%= link_to "Editar Perfil", edit_user_registration_path, class: "btn btn-outline-success my-2 my-sm-0 m-2" %>

        <p class="nav-item">
          <%= button_to "Cerrar sesión", destroy_user_session_path, method: :delete, class: "btn btn-outline-primary my-2 my-sm-0 m-2" %>
        </p>
      </div>
    </div>
  <% end %>
</nav>

Trabajo_final/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TrabajoFinal</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <%= javascript_include_tag :application %>

  <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  <%= javascript_importmap_tags %>
</head>

<style>
    input::-webkit-outer-spin-button,
    input::-webkit-inner-spin-button {
        /* display: none; <- Crashes Chrome on hover */
        -webkit-appearance: none;
        margin: 0; /* <-- Apparently some margin are still there even though it's hidden */
    }

    input[type=number] {
        -moz-appearance: textfield; /* Firefox */
    }

    * {
        font-size: 1.2rem;
    }

    h1 {
        color: #F7F7F7;
    }
</style>
<body class="bg-dark">
<%= render "layouts/navbar" %>
<div class="d-flex justify-content-center mt-3">
  <div>
    <% if user_signed_in? %>
      <% if alert %>
        <ul class="list-unstyled">
          <li class="alert alert-warning"><%= alert %></li>
        </ul>
      <% end %>
      <% if notice %>
        <ul class="list-unstyled">
          <li class="alert alert-info"><%= notice %></li>
        </ul>
      <% end %>
    <% end %>
  </div>
</div>
<%= yield %>
</body>
</html>